<a href="https://colab.research.google.com/github/GracielaVelez/tutoria/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**GRACIELA GUADALUPE VELEZ ZAMBRABO**

1. Import numpy as np and see the version

In [1]:
import numpy as np

2. Create a 1D array of numbers from 0 to 9

In [2]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.array([5, 7, 8, 3])

array([5, 7, 8, 3])

3. Create a 3×3 numpy array of all True’s

In [4]:
B=np.array([[2, 6, 9], [7, 7, 6],[6, 9, 2]])
print(B)

[[2 6 9]
 [7 7 6]
 [6 9 2]]


4. Extract all odd numbers from arr

In [5]:
B[B % 2 !=0]


array([9, 7, 7, 9])

In [6]:
B[B % 2==0]

array([2, 6, 6, 6, 2])

5. Replace all odd numbers in arr with -1

In [8]:
B[B % 2 !=0]=10
print(B)

[[ 2  6 10]
 [10 10  6]
 [ 6 10  2]]


6. Convert a 1D array to a 2D array with 2 rows

In [9]:
A2 = A.reshape(2,5)
A2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 7. Stack arrays a and b vertically

In [22]:
a=np.random.randint(low=4,high=18,size=(3,3))
b=np.random.randint(low=1,high=8,size=(3,3))
a

array([[ 8, 13, 15],
       [17,  8, 10],
       [ 7,  9, 12]])

In [13]:
b

array([[1, 2, 6],
       [7, 3, 7],
       [6, 2, 2]])

In [23]:
apilar=np.vstack((a,b)) #vertical
print(apilar)

[[ 8 13 15]
 [17  8 10]
 [ 7  9 12]
 [ 2  5  4]
 [ 6  7  5]
 [ 5  7  4]]


8. Stack the arrays a and b horizontally.

In [24]:
apilar=np.hstack((a,b)) #horizontal
print(apilar)

[[ 8 13 15  2  5  4]
 [17  8 10  6  7  5]
 [ 7  9 12  5  7  4]]


9. Get all items between 5 and 10 from a.

In [25]:
a

array([[ 8, 13, 15],
       [17,  8, 10],
       [ 7,  9, 12]])

In [29]:
filter=((a>5)&(a<10) )
print(a[filter])

[8 8 7 9]


10. How to make a python function that handles scalars to work on numpy arrays?

In [30]:
def maxx(x, y):
  if x >= y:
       return x
  else:
       return y
a= np.array([4,6,8,8,1,7,3])
b= np.array([6,4,4,1,6,5,3])

tmp=list()
for i in range(len(a)):
  tmp.append(maxx(a[i],b[i]))
print(tmp)

[6, 6, 8, 8, 6, 7, 3]


11. Swap columns 1 and 2 in the array arr.

In [46]:
B1 = np.arange(9).reshape(3,3)
print(B1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
# Intercambiar columnas 1 y 2
B1[:, [1, 2]] = B1[:, [2, 1]]

print(B1)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


#####3 12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [48]:
decimal = np.random.uniform(5, 10, (5, 3))

print(decimal)

[[7.90045578 6.16873505 9.93383917]
 [5.45058119 6.2016992  6.45646291]
 [6.63170021 5.35021901 7.14816485]
 [8.58567477 9.51550297 6.49650762]
 [5.5371585  6.46242452 9.60319634]]
