<a href="https://colab.research.google.com/github/GracielaVelez/tutoria/blob/main/tutorias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version
Python 3.10.12

In [ ]:
import numpy as np
tutorial=np.array([3,33,333])
print(tutorial)
print(tutorial.shape)

[  3  33 333]
(3,)


In [ ]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]])

print(b[:,[3,2]])

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=8,size=(2,2))


In [ ]:
c

array([[11,  8],
       [ 6,  4]])

In [ ]:
d

array([[2, 6],
       [4, 7]])

In [ ]:
aux=np.vstack((c,d))
print(aux)

[[11  8]
 [ 6  4]
 [ 3  6]
 [ 4  2]]


In [ ]:
au=np.hstack((c,d))
print(au)

[[11  8  3  6]
 [ 6  4  4  2]]


In [ ]:
a=np.random.randint(low=1,high=14,size=(9))
print(a)
print(a.shape)

[ 1 11  1  6 13 11  8 12 13]
(9,)


In [ ]:
filter=(a<3)
print(a[filter])

[1 1]


In [ ]:
a[a%2!=0]
print(a)

[ 1 11  1  6 13 11  8 12 13]


In [ ]:

def maxx(x, y):
  if x >= y:
       return x
  else:
       return y
a= np.array([5,7,9,8,6,4,5])
b= np.array([6,3,4,8,9,7,1])

tmp=list()
for i in range(len(a)):
  tmp.append(maxx(a[i],b[i]))
print(tmp)

[6, 7, 9, 8, 9, 7, 5]
